### ISSUE TITLE
缺少很多android settings.grade build.gradle 内容

### ISSUE THREAD

**Issue by marekchen** [songxiaoliang/ComicApp#1]
缺少很多android settings.grade build.gradle 内容:
例如：settings.grade中缺少
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

include ':react-native-blur'
project(':react-native-blur').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-blur/android')

**Comment by songxiaoliang** [comment]
不用加到setting啊，你只要正确引入并且save了，package.json中显示正确就可以了呀

**Comment by songxiaoliang** [comment]
哦，sorry。那个后来因为修改了，项目中没有使用到，可能有import忘记删除，但是不影响项目的正常使用。
