### ISSUE TITLE
请求的数据接口报错{ error_code: 10012, reason: "key请求次数超限！", result: "4b82308b740b32e1fd95e8818a730d3f" }

### ISSUE THREAD

**Issue by ysq1051838264** [songxiaoliang/ComicApp#8]
请求的数据接口报错如下
{
error_code: 10012,
reason: "key请求次数超限！",
result: "4b82308b740b32e1fd95e8818a730d3f"
}

**Comment by songxiaoliang** [comment]
恩，我用的是聚合数据的API，它有次数限制，不好意思哈。你可以自己申请一个即可。

**Comment by songxiaoliang** [comment]
我换了个新的，你重新pull一下即可。
