### ISSUE TITLE
react-native-vector-icons/Ionicons 图片名

### ISSUE THREAD

**Issue by youngcao2015** [songxiaoliang/ComicApp#9]
var tabIcons = ['ios-home', 'ios-compass', 'ios-heart', 'ios-contact'];
请问这个图片名是如何获得的？
到这个网站 http://ionicons.com 找到图片名似乎不可以直接用(去掉前面的ion-也是有的可以用，有的不行)？
谢谢！

**Comment by songxiaoliang** [comment]
进入ionic网站选择某个图标后点击进去，选择那个名字即可。

**Comment by youngcao2015** [comment]
@songxiaoliang 谢谢，找到了。

**Comment by songxiaoliang** [comment]
恩，具体的图标网址是：http://ionicframework.com/docs/ionicons/
